gitSourceBranch = "main"

[[classOrder]]
classes = [
    "RailUtil",
    "--------"
]

[[classOrder]]
classes = [
    "MathUtil",
    "VectorUtil",
    "StringUtil",
    "TableUtil",
    "InstanceUtil",
    "PlayerUtil",
    "CameraUtil",
    "SignalUtil",
]

[[classOrder]]
section = "InputUtil"
classes = ["InputUtil", "PreferredInput", "Mouse", "Keyboard", "Touch", "Gamepad"]

[[classOrder]]
section = "FusionUtil"
classes = ["FusionUtil", "[0.3.0] FusionUtil", "[0.2.5] FusionUtil", "[0.2.0] FusionUtil"]

[[classOrder]]
classes = [
    "DrawUtil",
    "DebugUtil",
]